import {
  Anchor,
  Box,
  Code2,
  Database,
  Eye,
  Frame,
  Grid3x3,
  Hexagon,
  Image as ImageIcon,
  Joystick,
  Keyboard,
  Layers,
  Monitor,
  Network,
  Orbit,
  Palette,
  QrCode,
  Ruler,
  Sparkles,
  Terminal,
  Upload,
  Video,
  Wand2,
  X as XIcon,
  Zap,
  ZoomIn,
  type LucideIcon,
} from "lucide-react";

/** One design/tech-flavored icon per letter — a shared visual theme for anything that shows letters-as-icons (Cryptogram, the hero title flip). */
export const LETTER_ICONS: Record<string, LucideIcon> = {
  A: Anchor,
  B: Box,
  C: Code2,
  D: Database,
  E: Eye,
  F: Frame,
  G: Grid3x3,
  H: Hexagon,
  I: ImageIcon,
  J: Joystick,
  K: Keyboard,
  L: Layers,
  M: Monitor,
  N: Network,
  O: Orbit,
  P: Palette,
  Q: QrCode,
  R: Ruler,
  S: Sparkles,
  T: Terminal,
  U: Upload,
  V: Video,
  W: Wand2,
  X: XIcon,
  Y: Zap,
  Z: ZoomIn,
};
