import {
  Anchor,
  Box,
  Code2,
  Database,
  Eye,
  Frame,
  Grid3x3,
  Hexagon,
  Image as ImageIcon,
  Joystick,
  Keyboard,
  Layers,
  Monitor,
  Network,
  Orbit,
  Palette,
  QrCode,
  Ruler,
  Sparkles,
  Terminal,
  Upload,
  Video,
  Wand2,
  X as XIcon,
  Zap,
  ZoomIn,
  Paintbrush,
  Crop,
  PenTool,
  MousePointer2,
  LayoutGrid,
  Shapes,
  Component,
  Move,
  Contrast,
  Pipette,
  Scissors,
  Type,
  Globe,
  Maximize2,
  Smartphone,
  Award,
  Briefcase,
  TrendingUp,
  DollarSign,
  LineChart,
  Flag,
  Target,
  Handshake,
  BarChart3,
  Trophy,
  Gauge,
  Landmark,
  Building2,
  Navigation,
  PieChart,
  PiggyBank,
  Compass,
  Rocket,
  Star,
  CreditCard,
  Users,
  CheckCircle2,
  Coins,
  Banknote,
  ThumbsUp,
  Map,
  type LucideIcon,
} from "lucide-react";

/** One design/tech-flavored icon per letter — the general-purpose set (Cryptogram). */
export const LETTER_ICONS: Record<string, LucideIcon> = {
  A: Anchor,
  B: Box,
  C: Code2,
  D: Database,
  E: Eye,
  F: Frame,
  G: Grid3x3,
  H: Hexagon,
  I: ImageIcon,
  J: Joystick,
  K: Keyboard,
  L: Layers,
  M: Monitor,
  N: Network,
  O: Orbit,
  P: Palette,
  Q: QrCode,
  R: Ruler,
  S: Sparkles,
  T: Terminal,
  U: Upload,
  V: Video,
  W: Wand2,
  X: XIcon,
  Y: Zap,
  Z: ZoomIn,
};

/** Core design/UI-tool icons — used for the hero title's "design" half. */
export const DESIGN_LETTER_ICONS: Record<string, LucideIcon> = {
  A: Anchor,
  B: Paintbrush,
  C: Crop,
  D: PenTool,
  E: MousePointer2,
  F: Frame,
  G: LayoutGrid,
  H: Hexagon,
  I: ImageIcon,
  J: Shapes,
  K: Component,
  L: Layers,
  M: Move,
  N: Contrast,
  O: Palette,
  P: Pipette,
  Q: Scissors,
  R: Ruler,
  S: Sparkles,
  T: Type,
  U: Globe,
  V: Maximize2,
  W: Wand2,
  X: XIcon,
  Y: Smartphone,
  Z: ZoomIn,
};

/** Business/growth-flavored icons — used for the hero title's "achieve your goals" half. */
export const BUSINESS_LETTER_ICONS: Record<string, LucideIcon> = {
  A: Award,
  B: Briefcase,
  C: TrendingUp,
  D: DollarSign,
  E: LineChart,
  F: Flag,
  G: Target,
  H: Handshake,
  I: BarChart3,
  J: Trophy,
  K: Gauge,
  L: Landmark,
  M: Building2,
  N: Navigation,
  O: PieChart,
  P: PiggyBank,
  Q: Compass,
  R: Rocket,
  S: Star,
  T: CreditCard,
  U: Users,
  V: CheckCircle2,
  W: Coins,
  X: Banknote,
  Y: ThumbsUp,
  Z: Map,
};
