import { defineArrayMember, defineField, defineType } from "sanity";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "meta", title: "Info & Meta" },
    { name: "scale", title: "Scale & Scores" },
    { name: "blocks", title: "Page blocks" },
  ],
  fields: [
    defineField({ name: "name", type: "string", group: "content", validation: (r) => r.required() }),
    defineField({
      name: "slug",
      type: "slug",
      group: "content",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "oneLiner",
      type: "text",
      rows: 2,
      group: "content",
      validation: (r) => r.required(),
    }),
    defineField({ name: "coverImage", type: "image", group: "content", options: { hotspot: true } }),
    defineField({
      name: "coverGif",
      title: "Cover GIF",
      type: "image",
      group: "content",
      description: "Optional animated cover — shown instead of the static cover image when set.",
    }),
    defineField({
      name: "showOnPortfolio",
      title: "Show on portfolio",
      type: "boolean",
      group: "content",
      initialValue: true,
      description: "Turn off to hide this project everywhere on the live site without deleting it.",
    }),
    defineField({
      name: "blocks",
      title: "Page blocks",
      type: "array",
      group: "blocks",
      of: [
        { type: "sectionBreak" },
        { type: "hero" },
        { type: "metricsRow" },
        { type: "richText" },
        { type: "sideBySideCards" },
        { type: "imageGallery" },
        { type: "chart" },
        { type: "quote" },
        { type: "processTimeline" },
        { type: "fullBleedImage" },
        { type: "imageGrid" },
        { type: "video" },
        { type: "textGrid" },
        { type: "pipLinkPreview" },
      ],
    }),
    defineField({
      name: "industry",
      type: "reference",
      to: [{ type: "industry" }],
      group: "meta",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "tags",
      type: "array",
      group: "meta",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "projectType",
      title: "Project type",
      type: "string",
      group: "meta",
      options: {
        list: ["Dashboard", "App", "Website", "Branding", "Campaign"].map((v) => ({
          title: v,
          value: v,
        })),
      },
      validation: (r) => r.required(),
    }),
    defineField({ name: "year", type: "number", group: "meta", validation: (r) => r.required() }),
    defineField({ name: "role", type: "string", group: "meta", validation: (r) => r.required() }),
    defineField({
      name: "techStack",
      type: "array",
      group: "meta",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "links",
      title: "Links",
      type: "array",
      group: "meta",
      description:
        "Shown as outline buttons at the top of the project page, under the role/year/industry row.",
      of: [
        defineArrayMember({
          type: "object",
          name: "projectLink",
          fields: [
            defineField({ name: "label", type: "string", validation: (r) => r.required() }),
            defineField({ name: "url", type: "url", validation: (r) => r.required() }),
          ],
          preview: { select: { title: "label", subtitle: "url" } },
        }),
      ],
    }),
    defineField({ name: "valueImpact", type: "valueImpact", group: "meta" }),
    defineField({ name: "accent", type: "projectAccent", group: "meta" }),
    defineField({
      name: "aiContext",
      title: "AI context",
      type: "text",
      rows: 6,
      group: "meta",
      description: "Reference notes for FaveAI to draw on when answering questions about this project — not shown on the page itself.",
    }),
    defineField({
      name: "scale",
      title: "Scale & scope metrics",
      type: "array",
      group: "scale",
      description:
        "Shown in the case-study sidebar's \"Scope at a glance\" card. Add any number + label pair you want — not fixed to specific fields.",
      of: [
        defineArrayMember({
          type: "object",
          name: "scaleMetric",
          fields: [
            defineField({ name: "value", type: "string", validation: (r) => r.required() }),
            defineField({ name: "label", type: "string", validation: (r) => r.required() }),
          ],
          preview: { select: { title: "value", subtitle: "label" } },
        }),
      ],
    }),
    defineField({
      name: "complexity",
      type: "number",
      group: "scale",
      description: "Carried over from the old portfolio — a 0-10 self-rated complexity score.",
    }),
    defineField({
      name: "recency",
      type: "number",
      group: "scale",
      description: "Carried over from the old portfolio — a 0-10 self-rated recency/relevance score.",
    }),
    defineField({
      name: "cardSize",
      title: "Card size (Projects grid)",
      type: "string",
      group: "scale",
      description: "Controls how much room this project's card takes in the /projects mosaic grid.",
      options: {
        list: [
          { title: "Small", value: "small" },
          { title: "Wide", value: "wide" },
          { title: "Tall", value: "tall" },
          { title: "Large", value: "large" },
        ],
      },
      initialValue: "small",
    }),
    defineField({
      name: "processDisciplines",
      title: "Relevant process disciplines",
      type: "array",
      group: "scale",
      description: "Which /process tracks to show as horizontal tabs on this case study page.",
      of: [{ type: "string" }],
      options: {
        list: ["Overall", "UI/UX", "Web Development", "Branding", "Campaigns & Marketing"].map((v) => ({
          title: v,
          value: v,
        })),
      },
    }),
  ],
  preview: {
    select: { title: "name", industryName: "industry.name", media: "coverImage", hidden: "showOnPortfolio" },
    prepare: ({ title, industryName, media, hidden }) => ({
      title,
      subtitle: hidden === false ? `${industryName} — hidden` : industryName,
      media,
    }),
  },
});
